name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # チェックアウト
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Go をセットアップ
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      # リリース
      - uses: goreleaser/goreleaser-action@v6
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}